### ISSUE TITLE
Switch to use Jason

### ISSUE THREAD

**Issue by codeadict** [rentpath/ex_json_logger#13]
Most of the other Elixir packages are moving to Jason as a dependency, it will be nice to use Jason for this package because is faster than Poison, or way better, have the `encode()` method in a behaviour and let the users decide which package will be used for encoding.

**Comment by doomspork** [comment]
@codeadict would you be willing to submit a PR migrating the project to Jason?

**Comment by codeadict** [comment]
Sure I do, will need to wait until the weekend though.

**Comment by doomspork** [comment]
That would be a wonderful and welcome contribution @codeadict 👍
