### ISSUE TITLE
`compile_time_purge_level`

### ISSUE THREAD

**Issue by Ebtoulson** [rentpath/ex_json_logger#2]
Investigate `Logger`s `compile_time_purge_level` configuration and if we need to adjust the ecto log. My initial thought is no because we're using `Logger.log`

**Comment by ruslandoga** [comment]
👋 @Ebtoulson 

I think this can be closed since the Ecto.Repo has deprecated loggers and is using telemetry now.

**Comment by Stratus3D** [comment]
Closing as I don't think this is relevant to ex_json_logger. `compile_time_purge_level` can be used regardless of the log formatter used.
